name: Schedule Workflow

on:
  schedule:
    - cron: '* * * * *'

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
